In [1]:
import numpy as np
from scipy.linalg import solve_triangular as st

In [2]:
def solve_tri(A, b, lower=False):
    n = len(A)
    for i in range(0, n-2):
        if A[n-1][i] != 0:
            lower = True  # determining whether the matrix is lower triangle or not
    nn1 = A.shape  # number of equations
    nn2 = b.shape
    xx = np.zeros(n, float)
    if nn1[1] != nn2[0]:
        return print("The matrices' dimensions do not coincide.")
    else:        
        if not lower:
            xx[n-1] = b[n-1] / A[n-1, n-1]
            for i in range(n - 2, -1, -1):
                sum = b[i]
                for j in range(i + 1, n):
                    sum = sum - A[i, j] * xx[j]
                xx[i] = sum / A[i, i]
        else:
            xx[0] = b[0] / A[0, 0]
            for i in range(1, n):
                sum = b[i]
                for j in range(i-1, -1, -1):
                    sum = sum - A[i, j] * xx[j]
                xx[i] = sum / A[i, i]
        return xx

In [3]:
A = np.array([[10, 2, 1, 1], [0, 10, 4, 5], [0, 0, 7, 3], [0, 0, 0, 4]], dtype=float)
AA = np.array([[4, 0, 0, 0], [3, 7, 0, 0], [5, 4, 10, 0], [1, 1, 2, 10]], dtype=float)
b = np.array([1, 2, 3, 4], dtype=float)
print(A, b)
print(AA, b)
x = st(A, b, lower=False)
xx = st(AA, b, lower=True)

print("The answer is: ", solve_tri(A, b))
print("The answer is: ", solve_tri(AA, b))
print(x)
print(xx)

[[10.  2.  1.  1.]
 [ 0. 10.  4.  5.]
 [ 0.  0.  7.  3.]
 [ 0.  0.  0.  4.]] [1. 2. 3. 4.]
[[ 4.  0.  0.  0.]
 [ 3.  7.  0.  0.]
 [ 5.  4. 10.  0.]
 [ 1.  1.  2. 10.]] [1. 2. 3. 4.]
The answer is:  [ 0.06 -0.3   0.    1.  ]
The answer is:  [0.25       0.17857143 0.10357143 0.33642857]
[ 0.06 -0.3   0.    1.  ]
[0.25       0.17857143 0.10357143 0.33642857]


In [4]:
A = np.array([[101, 21, 11, 11], [0, 101, 41, 51], [0, 0, 71, 31], [0, 0, 0, 41]], dtype=float)
AA = np.array([[41, 0, 0, 0], [31, 71, 0, 0], [51, 41, 101, 0], [11, 11, 21, 101]], dtype=float)
b = np.array([11, 21, 31, 41], dtype=float)
print(A, b)
print(AA, b)
x = st(A, b, lower=False)
xx = st(AA, b, lower=True)

print("The answer is: ", solve_tri(A, b))
print("The answer is: ", solve_tri(AA, b))
print(x)
print(xx)

[[101.  21.  11.  11.]
 [  0. 101.  41.  51.]
 [  0.   0.  71.  31.]
 [  0.   0.   0.  41.]] [11. 21. 31. 41.]
[[ 41.   0.   0.   0.]
 [ 31.  71.   0.   0.]
 [ 51.  41. 101.   0.]
 [ 11.  11.  21. 101.]] [11. 21. 31. 41.]
The answer is:  [ 0.06175865 -0.2970297   0.          1.        ]
The answer is:  [0.26829268 0.17863277 0.09894188 0.33669347]
[ 0.06175865 -0.2970297   0.          1.        ]
[0.26829268 0.17863277 0.09894188 0.33669347]
